name: Trigger auto deployment for container-app-jyzf2jrgwd4ws

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'fastify-api-server/**'
    - '.github/workflows/container-app-jyzf2jrgwd4ws-AutoDeployTrigger-ecbbad85-8c63-4ff1-a195-dc4c4d704dc2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPJYZF2JRGWD4WS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPJYZF2JRGWD4WS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPJYZF2JRGWD4WS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/fastify-api-server 
          registryUrl: defaultacrcontainerregistrya7fe.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPJYZF2JRGWD4WS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPJYZF2JRGWD4WS_REGISTRY_PASSWORD }}
          containerAppName: container-app-jyzf2jrgwd4ws
          resourceGroup: shopathomesvelteaf1cb10d
          imageToBuild: defaultacrcontainerregistrya7fe.azurecr.io/container-app-jyzf2jrgwd4ws:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


